listen: "127.0.0.1:25577"
authentication: OFFLINE
maxConnections: 4096
plugins:
  directory: "../plugins"
  initialPlacementTimeoutSeconds: 15
  eventTimeoutSeconds: 5
  enabled: {}
backends:
  - name: "lobby"
    address: "127.0.0.1:25565"
    tags:
      role: "lobby"
